name: Build & Push

on:
  push:
    branches:
     - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and upload Docker images
      run: |
        dockerfiles=$(find . -maxdepth 1 -name "Dockerfile.*")
        for dockerfile in $dockerfiles; do
          image_name="${dockerfile#./Dockerfile.}"
          docker build -t ghcr.io/$( echo "${{ github.repository }}" | awk '{print tolower($0)}' )/$image_name:latest -f $dockerfile .
          docker push ghcr.io/$( echo "${{ github.repository }}" | awk '{print tolower($0)}' )/$image_name:latest
        done
